# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
