# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='page_name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=600),
        ),
    ]
