# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170611_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feed_title',
            field=models.TextField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
