# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_feed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='feed_title',
            field=models.CharField(max_length=300),
        ),
    ]
