# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gallery',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
